# Generated by Django 3.2.12 on 2023-05-21 17:16

from django.db import migrations, models
import django.db.models.deletion
import dvadmin.system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelist',
            name='engine',
            field=models.CharField(blank=True, default='local', help_text='引擎', max_length=100, verbose_name='引擎'),
        ),
        migrations.AddField(
            model_name='filelist',
            name='file_url',
            field=models.CharField(blank=True, help_text='文件地址', max_length=255, verbose_name='文件地址'),
        ),
        migrations.AddField(
            model_name='filelist',
            name='mime_type',
            field=models.CharField(blank=True, help_text='Mime类型', max_length=100, verbose_name='Mime类型'),
        ),
        migrations.AddField(
            model_name='filelist',
            name='size',
            field=models.CharField(blank=True, help_text='文件大小', max_length=36, verbose_name='文件大小'),
        ),
        migrations.AddField(
            model_name='users',
            name='employee_no',
            field=models.CharField(blank=True, db_index=True, help_text='工号', max_length=150, null=True, unique=True, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='users',
            name='last_token',
            field=models.CharField(blank=True, help_text='最后一次登录Token', max_length=255, null=True, verbose_name='最后一次登录Token'),
        ),
        migrations.AlterField(
            model_name='area',
            name='pcode',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='父地区编码', null=True, on_delete=django.db.models.deletion.PROTECT, to='system.area', to_field='code', verbose_name='父地区编码'),
        ),
        migrations.AlterField(
            model_name='filelist',
            name='url',
            field=models.FileField(blank=True, null=True, upload_to=dvadmin.system.models.media_file_name),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='login_type',
            field=models.IntegerField(choices=[(1, '普通登录'), (2, '普通扫码登录'), (3, '微信扫码登录'), (4, '飞书扫码登录'), (5, '钉钉扫码登录'), (6, '短信登录')], default=1, help_text='登录类型', verbose_name='登录类型'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='username',
            field=models.CharField(blank=True, help_text='登录用户名', max_length=150, null=True, verbose_name='登录用户名'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='上级菜单', null=True, on_delete=django.db.models.deletion.PROTECT, to='system.menu', verbose_name='上级菜单'),
        ),
        migrations.AlterField(
            model_name='menubutton',
            name='menu',
            field=models.ForeignKey(db_constraint=False, help_text='关联菜单', on_delete=django.db.models.deletion.PROTECT, related_name='menuPermission', to='system.menu', verbose_name='关联菜单'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(db_index=True, help_text='键', max_length=200, verbose_name='键'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='父级', null=True, on_delete=django.db.models.deletion.PROTECT, to='system.systemconfig', verbose_name='父级'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='placeholder',
            field=models.CharField(blank=True, help_text='提示信息', max_length=100, null=True, verbose_name='提示信息'),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='value',
            field=models.JSONField(blank=True, help_text='值', max_length=500, null=True, verbose_name='值'),
        ),
    ]
