# Generated by Django 3.2.12 on 2023-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20230521_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='access_key',
            field=models.CharField(blank=True, help_text='AK', max_length=256, null=True, verbose_name='AK'),
        ),
        migrations.AddField(
            model_name='dept',
            name='secret_key',
            field=models.CharField(blank=True, help_text='SK', max_length=256, null=True, verbose_name='SK'),
        ),
    ]
