# Generated by Django 3.2.12 on 2023-06-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_dept_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='dashboard_url',
            field=models.CharField(blank=True, help_text='DASHBOARD', max_length=512, null=True, verbose_name='DASHBOARD'),
        ),
    ]
