# Generated by Django 3.2.12 on 2023-06-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_billing_conductor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awsbillingconductorgroupmodel',
            options={'ordering': ('creation_time',), 'verbose_name': '账单组表', 'verbose_name_plural': '账单组表'},
        ),
        migrations.RemoveField(
            model_name='awsbillingconductorgroupmodel',
            name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='awsbillingconductorgroupmodel',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='awsbillingconductorgroupmodel',
            name='dept_belong_id',
        ),
        migrations.RemoveField(
            model_name='awsbillingconductorgroupmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='awsbillingconductorgroupmodel',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='awsbillingconductorgroupmodel',
            name='update_datetime',
        ),
        migrations.AlterField(
            model_name='awsbillingconductorgroupmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
